#!/usr/bin/env bash
# Bash script to configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

apt-get -y update
apt-get -y install nginx


if ! nginx -v
then
        exit
fi


repl_dir="\t\tadd_header X-Served-By \$hostname;\n\t}"
path_config="/etc/nginx/sites-available/default"

#This sed command only replaces the first occurence of a tabbed right brace
sed -i -r "0,/^\t}$/{s//$repl_dir/}" $path_config

service nginx restart
