#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

dump_name="backup.sql"
archive_name="$(date +'%d-%m-%Y').tar.gz"
mysqldump -p"$1" -uroot --all-databases > "$dump_name"
tar -czvf "$archive_name" "$dump_name"
