#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.
#+ Displays I am invincible!!! upon receipt of a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM

while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
