#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i -E '1s/^# user.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pgrep apache2 | head -1 > /var/run/apache2/apache2.pid
service apache2 stop
su -c 'service nginx restart' nginx
