#!/usr/bin/env bash
# Run Nginx as Nginx
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i -E '1s/^#?user.*$/user nginx;/' /etc/nginx/nginx.conf
su -c 'service nginx restart' nginx
